---
title: "Mapa y Tabla interactivos"
language: "es-es"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(sp)
library(RColorBrewer)
library(leaflet)
library(DT)
library(dplyr)
```

### Mapa Interactivo

```{r echo=FALSE}
ub_argentina<-"gadm36_ARG_2_sp.rds"
argentina<-readRDS(ub_argentina)
salta<-argentina[argentina$NAME_1=="Salta",]
#contagios<-read.csv2('contagios covid salta.csv',header = T)[1:23,3]
salta@data<-data.frame(Departamentos=c('Anta','Cachi','Cafayate','Capital','Cerrillos','Chicoana','Gral. Guemes','Gral. San Martín','Guachipas','Iruya','La Caldera','La Candelaria','La Poma','La Viña','Los Andes','Metan','Molinos','Oran','Rivadavia','Rosario de la Frontera','Rosario de Lerma','San Carlos','Santa Victoria'),contagios=c(20,0,5,717,38,19,188,901,3,7,23,0,0,19,12,11,0,486,69,4,41,1,3))
#spplot(salta,col.regions=hcl.colors(47,palette = 'harmonic',rev = T))
x<-colorNumeric('Reds',NULL)
leaflet(salta, options =
               leafletOptions(attributionControl = FALSE, minzoom=1.5)) %>%
  addPolygons(
    label=~salta$contagios,
    weight=1,color='#333333', opacity=1,
    fillColor = ~x(contagios), fillOpacity = 1,
    highlightOptions = highlightOptions(
      color='#000000', weight = 2,
      bringToFront = TRUE, sendToBack = TRUE)
    )%>%
  addLegend(
    "topright", pal =x, values = ~contagios,
    title = c('casos de Covid-19<br/>provincia de Salta'),
    opacity = 1 )
```

## Tabla de Datos

```{r echo=FALSE}
#contagios<-read.csv2('contagios covid salta.csv',header = T)
contagios<-data.frame(Departamentos=c('Anta','Cachi','Cafayate' ,'Capital','Cerrillos','Chicoana','Gral. Guemes','Gral. San Martín', 'Guachipas','Iruya','La Caldera','La Candelaria','La Poma','La Viña', 'Los Andes', 'Metan', 'Molinos', 'Oran', 'Rivadavia', 'Rosario de la Frontera','Rosario de Lerma','San Carlos','Santa Victoria', 'TOTAL') ,Casos = c(20,0,5,717,38,19,188,901,3,7,23,0,0,19,12,11,0,486,69,4,41,1,3,2567))
colnames(contagios)<-c("Departamento","Casos Acumulados")
datatable(contagios,class = 'cell-border')
```

